#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs THIS app draws, from the Phosphor core repo.
 *
 *   npm run icons
 *
 * From the source, never from another product's tree. A copy of a copy has no source to
 * re-read, and the estate has no shared component library to take one from: those repos were
 * purged on 2026-09-14 and every app vendors its own set.
 *
 * The list below is this app's own. Every glyph names one thing on this site: a destination,
 * a kind of input a tool takes, a state a row can be in, or a rail head. A glyph with no
 * caller is a glyph to delete rather than to keep in case.
 *
 * They compile into src/lib/phosphor.ts as path bodies in currentColor, so a glyph takes the
 * ink of whatever sits beside it. No icon font and no runtime CDN.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

const WANT = [
  'plugs-connected', // the console: a client joined to this server
  'table', // the full tool grid
  'file-text', // the method page
  'caret-up-down', // the app switch beside the mark
  'caret-right', // a row that opens
  'coins', // the credit wallet
  'lightning', // the masthead action
  'terminal-window', // a client configuration block
  'file-arrow-up', // a tool that takes a file or a URL
  'text-aa', // a tool that takes text
  'rows', // a tool that takes records
  'image', // a tool that takes an image
  'microphone', // a tool that takes audio
  'funnel', // the rail head that narrows the surface
  'prohibit', // the one endpoint that is paused
  'check', // a hint that holds
  'x', // a hint that does not
  'clock', // a read date
  'info', // a note in a rail
  'arrow-square-out', // an outward link
  'key', // the one environment variable
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name}  ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n` +
    `export type GlyphName = keyof typeof GLYPH;\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
